name: "Purge Stackpath CDN"
description: "Purge files from a Stackpath CDN with credentials"
branding:
  icon: "trash-2"
  color: "green"
inputs:
  clientId:
    description: "Client ID for Stackpath API"
    required: true
  clientSecret:
    description: "Client Secret for Stackpath API"
    required: true
  stackId:
    description: "Stack ID from Stackpath"
    required: true
  url:
    description: "URL to be purged, with full protocol"
    required: true
runs:
  using: "node12"
  main: "index.js"
